/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    "Intro",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "CLI",
      link: {
        type: "generated-index",
        description: "Examples demonstrating the usage of CLI commands.",
      },
      items: [{ type: "autogenerated", dirName: "cli" }],
    },
    {
      type: "category",
      label: "Design",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "design" }],
    },
    {
      type: "category",
      label: "AI Applications",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "ai-applications" }],
    },
    {
      type: "category",
      label: "Examples",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      label: "Build Cloud Images",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "build-cloud-image" }],
    },
    {
      type: "category",
      label: "Development Guidelines",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "Development-Guidelines" }],
    },
    {
      type: "category",
      label: "Developers",
      items: ["CONTRIBUTING", "DEVELOPGUIDE"],
    },
    "References",
  ],
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
  cloudDocSidebar: [
    "cloud/Intro",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "cloud/getting-started" }],
    },
    {
      type: "category",
      label: "APPs",
      link: {
        type: "generated-index",
        description: "APPS of the sealos cloud.",
      },
      items: [{ type: "autogenerated", dirName: "cloud/apps" }],
    },
    {
      type: "category",
      label: "Examples",
      link: {
        type: "generated-index",
        description: "Examples demonstrating the usage of sealos cloud.",
      },
      items: [{ type: "autogenerated", dirName: "cloud/examples" }],
    },
    {
      type: "category",
      label: "Design",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "cloud/design" }]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
