/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "doc",
      id: "Intro",
      // label: "介绍",
      label: "Intro",
    },
    {
      type: "category",
      // label: "快速开始",
      label: "Quick Start",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "quick-start" }],
    },
    {
      type: "category",
      // label: "更多示例",
      label: "Examples",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      // label: "平台组件",
      label: "Platform Components",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "platform-components" }],
    },
    {
      type: "category",
      // label: "集群生命周期管理",
      label: "Cluster Lifecycle Management",
      link: {
        type: "generated-index",
      },
      items: [
        "lifecycle-management/Intro",
        {
          type: "category",
          label: "Getting Started",
          link: {
            type: "generated-index",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/getting-started" }],
        },
        {
          type: "category",
          label: "CLI",
          link: {
            type: "generated-index",
            description: "Examples demonstrating the usage of CLI commands.",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/cli" }],
        },
        {
          type: "category",
          label: "Design",
          link: {
            type: "generated-index",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/design" }],
        },
        {
          type: "category",
          label: "Examples",
          link: {
            type: "generated-index",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/examples" }],
        },
        {
          type: "category",
          label: "Build Cloud Images",
          link: {
            type: "generated-index",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/build-cloud-image" }],
        },
        {
          type: "category",
          label: "Development Guidelines",
          link: {
            type: "generated-index",
          },
          items: [{ type: "autogenerated", dirName: "lifecycle-management/Development-Guidelines" }],
        },
        {
          type: "category",
          label: "Developers",
          items: ["lifecycle-management/CONTRIBUTING", "lifecycle-management/DEVELOPGUIDE"],
        },
        "lifecycle-management/References",
      ],
    },
    // {
    //   type: "category",
    //   label: "常见问题 (FAQ)",
    //   link: {
    //     type: "generated-index",
    //   },
    //   items: [{ type: "autogenerated", dirName: "faq" }],
    // },
    {
      type: "doc",
      id: "Community",
      // label: "社区",
      label: "Community",
    },
  ],
};

module.exports = sidebars;
